# Generated by Django 5.1.7 on 2025-04-04 14:41

import store.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_review_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="review_img/",
                validators=[store.validation.validate_image_file_size],
            ),
        ),
    ]
