# Generated by Django 5.1.7 on 2025-04-05 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_review_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
