# Generated by Django 5.1.7 on 2025-04-02 07:34

import store.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="review_img/",
                validators=[
                    store.validation.validate_cover_image_size,
                    store.validation.validate_image_file_size,
                ],
            ),
        ),
    ]
